### ISSUE TITLE
使用了镜像还是提示连接到Huggingface.co网络超时

### ISSUE THREAD

**Issue by Weigaa** [padeoe/hf-mirror-site#16]
我尝试运行的代码库为：
https://github.com/microsoft/DeepSpeed-MII/blob/main/mii/legacy/examples/benchmark/txt2img/mii-sd.py
我使用了镜像库介绍的所有方法引入镜像库替换掉原始链接，
但是还是出现了以下错误：
(wjtorch2.0.1) lthpc@lthpc-C01:~/nvmessd/wj/DeepSpeed-MII/mii/legacy/examples/benchmark/txt2img$ python mii-sd.py
[2024-03-02 14:56:39,014] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/home/lthpc/anaconda3/envs/wjtorch2.0.1/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lthpc/anaconda3/envs/wjtorch2.0.1/lib/python3.11/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/lthpc/anaconda3/envs/wjtorch2.0.1/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lthpc/anaconda3/envs/wjtorch2.0.1/lib/python3.11/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/lthpc/anaconda3/envs/wjtorch2.0.1/lib/python3.11/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/home/lthpc/anaconda3/envs/wjtorch2.0.1/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/home/lthpc/anaconda3/envs/wjtorch2.0.1/lib/python3.11/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/home/lthpc/anaconda3/envs/wjtorch2.0.1/lib/python3.11/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f4c8325fe90>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lthpc/anaconda3/envs/wjtorch2.0.1/lib/python3.11/site-packages/requests/adapters.py", line 487, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/lthpc/anaconda3/envs/wjtorch2.0.1/lib/python3.11/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/lthpc/anaconda3/envs/wjtorch2.0.1/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models?cursor=eyJfaWQiOnsiJGd0IjoiNjIxZmZkYzEzNjQ2OGQ3MDlmMTc4ZTA1In19 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4c8325fe90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lthpc/nvmessd/wj/DeepSpeed-MII/mii/legacy/examples/benchmark/txt2img/mii-sd.py", line 20, in <module>
    mii.deploy(task='text-to-image',
  File "/home/lthpc/anaconda3/envs/wjtorch2.0.1/lib/python3.11/site-packages/mii/legacy/deployment.py", line 72, in deploy
    mii_config = mii.config.MIIConfig(**mii_config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lthpc/anaconda3/envs/wjtorch2.0.1/lib/python3.11/site-packages/deepspeed/runtime/config_utils.py", line 56, in __init__
    super().__init__(**data)
  File "/home/lthpc/anaconda3/envs/wjtorch2.0.1/lib/python3.11/site-packages/pydantic/v1/main.py", line 339, in __init__
    values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lthpc/anaconda3/envs/wjtorch2.0.1/lib/python3.11/site-packages/pydantic/v1/main.py", line 1074, in validate_model
    v_, errors_ = field.validate(value, values, loc=field.alias, cls=cls_)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lthpc/anaconda3/envs/wjtorch2.0.1/lib/python3.11/site-packages/pydantic/v1/fields.py", line 881, in validate
    v, errors = self._validate_singleton(v, values, loc, cls)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lthpc/anaconda3/envs/wjtorch2.0.1/lib/python3.11/site-packages/pydantic/v1/fields.py", line 1098, in _validate_singleton
    return self._apply_validators(v, values, loc, cls, self.validators)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lthpc/anaconda3/envs/wjtorch2.0.1/lib/python3.11/site-packages/pydantic/v1/fields.py", line 1154, in _apply_validators
    v = validator(cls, v, values, self, self.model_config)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lthpc/anaconda3/envs/wjtorch2.0.1/lib/python3.11/site-packages/pydantic/v1/class_validators.py", line 337, in <lambda>
    return lambda cls, v, values, field, config: validator(v)
                                                 ^^^^^^^^^^^^
  File "/home/lthpc/anaconda3/envs/wjtorch2.0.1/lib/python3.11/site-packages/pydantic/v1/main.py", line 711, in validate
    return cls(**value)
           ^^^^^^^^^^^^
  File "/home/lthpc/anaconda3/envs/wjtorch2.0.1/lib/python3.11/site-packages/deepspeed/runtime/config_utils.py", line 56, in __init__
    super().__init__(**data)
  File "/home/lthpc/anaconda3/envs/wjtorch2.0.1/lib/python3.11/site-packages/pydantic/v1/main.py", line 339, in __init__
    values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lthpc/anaconda3/envs/wjtorch2.0.1/lib/python3.11/site-packages/pydantic/v1/main.py", line 1100, in validate_model
    values = validator(cls_, values)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lthpc/anaconda3/envs/wjtorch2.0.1/lib/python3.11/site-packages/mii/legacy/config.py", line 257, in validate_model_and_task
    mii.utils.check_if_task_and_model_is_valid(task, model)
  File "/home/lthpc/anaconda3/envs/wjtorch2.0.1/lib/python3.11/site-packages/mii/legacy/utils.py", line 102, in check_if_task_and_model_is_valid
    valid_task_models = _get_hf_models_by_type(None, task)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lthpc/anaconda3/envs/wjtorch2.0.1/lib/python3.11/site-packages/mii/legacy/utils.py", line 44, in _get_hf_models_by_type
    model_data["model_list"] = [
                               ^
  File "/home/lthpc/anaconda3/envs/wjtorch2.0.1/lib/python3.11/site-packages/mii/legacy/utils.py", line 44, in <listcomp>
    model_data["model_list"] = [
                               ^
  File "/home/lthpc/anaconda3/envs/wjtorch2.0.1/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 1488, in list_models
    for item in items:
  File "/home/lthpc/anaconda3/envs/wjtorch2.0.1/lib/python3.11/site-packages/huggingface_hub/utils/_pagination.py", line 44, in paginate
    r = session.get(next_page, headers=headers)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lthpc/anaconda3/envs/wjtorch2.0.1/lib/python3.11/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lthpc/anaconda3/envs/wjtorch2.0.1/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lthpc/anaconda3/envs/wjtorch2.0.1/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lthpc/anaconda3/envs/wjtorch2.0.1/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 67, in send
    return super().send(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lthpc/anaconda3/envs/wjtorch2.0.1/lib/python3.11/site-packages/requests/adapters.py", line 520, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models?cursor=eyJfaWQiOnsiJGd0IjoiNjIxZmZkYzEzNjQ2OGQ3MDlmMTc4ZTA1In19 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4c8325fe90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), '(Request ID: a295b267-db99-4ad1-989d-e1f58a186d15)')

好像还是去请求原始网站了？

**Comment by KimBioInfoStudio** [comment]
> 我使用了镜像库介绍的所有方法引入镜像库替换掉原始链接

Pls show us how you did this

**Comment by padeoe** [comment]
To use mirror endpoints for official Hugging Face libraries, such as `transformers` and `datasets`, execute the following code before importing the libraries. This operation may not be supported by other third-party libraries. Please debug and analyze to determine which line of code is actually used to download models/data.

```
import os
os.environ['HF_ENDPOINT'] = 'https://hf-mirror.com'
```
