### ISSUE TITLE
非侵入性的环境变量无法代理cdn-lfs

### ISSUE THREAD

**Issue by Vimos** [padeoe/hf-mirror-site#21]
使用`HF_ENDPOINT=https://hf-mirror.com` 会转到` cdn-lfs.hf-mirror.com `进而

```python
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/vimos/git/FActScore/factscore/download_data.py", line 142, in <module>
    recover_instruct_llama(args.llama_7B_HF_path, os.path.join(args.model_dir, "inst-llama-7B"))
  File "/home/vimos/git/FActScore/factscore/download_data.py", line 77, in recover_instruct_llama
    model_recovered = transformers.AutoModelForCausalLM.from_pretrained(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vimos/anaconda3/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 566, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vimos/anaconda3/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3483, in from_pretrained
    resolved_archive_file, sharded_metadata = get_checkpoint_shard_files(
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vimos/anaconda3/lib/python3.11/site-packages/transformers/utils/hub.py", line 1025, in get_checkpoint_shard_files
    cached_filename = cached_file(
                      ^^^^^^^^^^^^
  File "/home/vimos/anaconda3/lib/python3.11/site-packages/transformers/utils/hub.py", line 385, in cached_file
    resolved_file = hf_hub_download(
                    ^^^^^^^^^^^^^^^^
  File "/home/vimos/anaconda3/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/vimos/anaconda3/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1492, in hf_hub_download
    http_get(
  File "/home/vimos/anaconda3/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 471, in http_get
    r = _request_wrapper(
        ^^^^^^^^^^^^^^^^^
  File "/home/vimos/anaconda3/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 408, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vimos/anaconda3/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vimos/anaconda3/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vimos/anaconda3/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 67, in send
    return super().send(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vimos/anaconda3/lib/python3.11/site-packages/requests/adapters.py", line 553, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: (MaxRetryError("HTTPSConnectionPool(host='cdn-lfs.hf-mirror.com', port=443): Max retries exceeded with url: /repos/ad/66/ad663190fd14ccc1286ab79b783a00c3e9b7f0f331e774a77654eae4aa316450/c2bcfc95fdb12e1d7cbeb069114cb262222bf363c52c559d989c0d33a373cee9?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27pytorch_model-00001-of-00003.bin%3B+filename%3D%22pytorch_model-00001-of-00003.bin%22%3B&response-content-type=application%2Foctet-stream&Expires=1711871151&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcxMTg3MTE1MX19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5odWdnaW5nZmFjZS5jby9yZXBvcy9hZC82Ni9hZDY2MzE5MGZkMTRjY2MxMjg2YWI3OWI3ODNhMDBjM2U5YjdmMGYzMzFlNzc0YTc3NjU0ZWFlNGFhMzE2NDUwL2MyYmNmYzk1ZmRiMTJlMWQ3Y2JlYjA2OTExNGNiMjYyMjIyYmYzNjNjNTJjNTU5ZDk4OWMwZDMzYTM3M2NlZTk~cmVzcG9uc2UtY29udGVudC1kaXNwb3NpdGlvbj0qJnJlc3BvbnNlLWNvbnRlbnQtdHlwZT0qIn1dfQ__&Signature=Z8zwygBnncPCjrNOKK2yVKBjzFRWkyUr2FDIy4Q1qs2V2t2PKHGKx6j1K7XeDGbVEcEOJOSjFs12kjYCdeQUINRqvXxwDO9UjJhR553HXJ1O1vSBkQMHKRwymSrNdAba5gPLCA1scibOANcGzhrkKZqii6p3B33Q1Vh1OOOduWE1bykKTVVpKVZtsCXyzc9afFZjKod9GpdYhXnO46wd-QOKOQj9gWd3j7RM~5orijpJFRTv2F6k0huPgprafAuYNPzS788-M3Ut4IquBNrbMgUwEuIb-jj~wdbWy3jb5uCfA2dWijDEr-tG0lwA9Nf5ci-W58lRA-LeoaUNZ1lZwA__&Key-Pair-Id=KVTP0A1DKRTAX (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7569113f2e50>, 'Connection to cdn-lfs.hf-mirror.com timed out. (connect timeout=10)'))"), '(Request ID: 9e24a2bf-44e5-463b-ad5c-409b5265e242)')
```

**Comment by padeoe** [comment]
这个跳转是正常的，根据你提供的日志，问题出在跳转后的网址连接超时了，可能是线路问题

**Comment by Guojing6** [comment]
> 这个跳转是正常的，根据你提供的日志，问题出在跳转后的网址连接超时了，可能是线路问题

你好，这种情况该怎么解决呀

**Comment by iseesaw** [comment]
同样出现这个问题，还挺频繁的
